---
title: "Wildfires"
author: "Michael Schmidt"
date: "8/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(geojsonio)
library(sf)
library(rnaturalearth)
library(schmidtytheme)


theme_set(theme_schmidt()+
            theme(
              panel.grid.major = element_line(colour = "transparent")
            ))


wildfires<-geojson_read("https://opendata.arcgis.com/datasets/5da472c6d27b4b67970acc7b5044c862_0.geojson", what="sp")%>%
  st_as_sf()

usa <- ne_states(country="united states of america", returnclass="sf")

colorado<-usa%>%
  filter(name=="Colorado")

the_west<-usa%>%
  filter(name %in% c("California", "Oregon", "Washington", "New Mexico", "Arizona", "Nevada", "Idaho", "Wyoming","Montana", "Utah", "Colorado"))
  

ggplot()+
  geom_sf(data=the_west, fill="#333333", color="#efefef")+
  geom_sf(data = wildfires, fill="#FF6A5D", color=NA)+
  coord_sf(xlim = c(-125, -101), ylim = c(30, 50), expand = FALSE)+
  labs(
    title = "Wildfires Burning in the West",
    x="",
    y="",
    subtitle="Date:8/27/2020",
    caption="@mschmidty | Data: National Inter Agency Fire Center"
  )+
  theme(
    plot.background=element_rect(fill = "#f9f9f9", colour = NA),
    axis.text=element_blank(),
    panel.border=element_blank(),
    axis.line=element_blank(),
    plot.title=element_text(size=20)
  )+
  ggsave("Wildfires_in_the_west.png", h=11, w=11, type="cairo")

```

## Historic Wildfires
```{r}

hist<-geojson_read("https://opendata.arcgis.com/datasets/4454e5d8e8c44b0280258b51bcf24794_0.geojson", what="sp")


```

