---
title: "Ridgline plot"
author: "Michael Schmidt"
date: "9/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(elevatr)
library(rnaturalearth)
library(raster)
library(conflicted)
library(ggridges)
library(schmidtytheme)
library(here)

theme_set(theme_schmidt()+
            theme(
              text=element_text(family="Public Sans Regular"),
              plot.title=element_text(family="Ultra", size=30)
            ))

conflict_prefer("select", "dplyr")
conflict_prefer("extract", "raster")
conflict_prefer("filter", "dplyr")
```

```{r}
colorado<-ne_states("United States of America", returnclass="sf")%>%
  filter(name=="Colorado")

state_dem<-get_elev_raster(as(colorado, "Spatial"), z = 6)%>%
  crop(colorado)

plot(state_dem)

background_color = "#121212"

state_dem%>%
  crop(extent(-110.9452, -105.7399, 36.99985, 38.00165))%>%
  rasterToPoints()%>%
  as_tibble()%>%
  rename(z=3)%>%
  mutate(z=z-min(z))%>%
  ggplot(aes(x, y, height=z, group=y))+
  geom_density_ridges(stat = "identity", scale = 20, color = "white", fill = background_color)+
  labs(x="",
       y = "")+
  theme(
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    panel.background=element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill=background_color),
    panel.grid.major = element_line(colour = "transparent"),
    panel.grid.minor = element_line(color = "transparent")
  )

```

#
```{r}
utah<-ne_states("United States of America", returnclass="sf")%>%
  filter(name=="Utah")

utah_dem<-get_elev_raster(as(utah, "Spatial"), z = 6)%>%
  crop(utah)

utah_dem%>%
  crop(extent(-112.5, -111.3, 40, 41.5))%>%
  rasterToPoints()%>%
  as_tibble()%>%
  rename(z=3)%>%
  mutate(z=z-min(z))%>%
  ggplot(aes(x, y, height=z, group=y))+
  geom_density_ridges(stat = "identity", scale = 20, color = "#fdfdfd", fill = "#232323")+
  labs(x="",
       y = "")+
  theme(
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    panel.background=element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill="#232323", color = NA),
    panel.grid.major = element_line(colour = "transparent"),
    panel.grid.minor = element_line(color = "transparent")
  )+
  ggsave(here("Dropbox","r","maps", "plots", paste0("ridgeline_wasatch_dark_", Sys.Date(),".jpg")), type = "cairo")


```


## White Ridgeline Plot

```{r}
background_color <-"#fdfdfd"
utah_dem%>%
  crop(extent(-112.5, -111.3, 40, 41.5))%>%
  rasterToPoints()%>%
  as_tibble()%>%
  rename(z=3)%>%
  mutate(z=z-min(z))%>%
  ggplot(aes(x, y, height=z, group=y))+
  geom_density_ridges(stat = "identity", scale = 20, color = "#333333", fill = background_color)+
  labs(x="",
       y = "")+
  theme(
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    panel.background=element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill=background_color, color = NA),
    panel.grid.major = element_line(colour = "transparent"),
    panel.grid.minor = element_line(color = "transparent")
  )+
  ggsave(here("Dropbox","r","maps", "plots", paste0("ridgeline_wasatch_light_", Sys.Date(),".svg")))
```

```{r}
nevada<-ne_states("United States of America", returnclass="sf")%>%
  filter(name=="Nevada")

nevada_dem<-get_elev_raster(as(nevada, "Spatial"), z = 6)%>%
  crop(nevada)

plot(nevada_dem)

nevada_dem%>%
  crop(extent(-118.5, -117.3, 40, 42))%>%
  rasterToPoints()%>%
  as_tibble()%>%
  rename(z=3)%>%
  mutate(z=z-min(z))%>%
  ggplot(aes(x, y, height=z, group=y))+
  geom_density_ridges(stat = "identity", scale = 30, color = "#333333", fill = background_color)+
  labs(title="Black Rock Desert",
       x="",
       y = "")+
  theme(
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    panel.background=element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill=background_color, color = NA),
    panel.grid.major = element_line(colour = "transparent"),
    panel.grid.minor = element_line(color = "transparent"), 
    text=element_text(family="Ultra"),
    plot.title=element_text(size=30)
  )

Sys.Date()
```


## Height colors

```{r}
utah_dem%>%
  crop(extent(-112.5, -111.3, 40, 41.5))%>%
  rasterToPoints()%>%
  as_tibble()%>%
  rename(z=3)%>%
  mutate(z=z-min(z))%>%
  ggplot(aes(x, y, height=z, group=y))+
  geom_density_ridges(stat = "identity", scale = 20, fill = "#232323", color = "#efefef")+
  labs(x="",
       y = "")+
  theme(
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    panel.background=element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill="#232323", color = NA),
    panel.grid.major = element_line(colour = "transparent"),
    panel.grid.minor = element_line(color = "transparent")
  )
```


